#!/usr/bin/env python

import sys
import os

machine = sys.argv[0].split("/")[-1]

sim = "simfactory/bin/sim"

def runcmd(args):
    cmd = " ".join(args)
    os.system(cmd)

cmd = sys.argv[1]

if cmd == "sync":
    runcmd([sim, "sync", machine])
else:
    if cmd in ["create", "create-run", "create-submit"]:
        runcmd([sim, "sync", "--sync-parfiles", machine])
    elif cmd in ["build"]:
        runcmd([sim, "sync", "--sync-sourcetree", machine])
    
    args = [sim, "--remote", machine]
    args.extend(sys.argv[1:])
    runcmd(args)
