#! /bin/bash

#PBS -l nodes=6:ppn=20

#PBS @('@CHAINED_JOB_ID@' != '' ? '-W depend=afterany:@CHAINED_JOB_ID@' : '')@

#PBS -N ModernFamily

#PBS -q batch

#PBS -j oe

cd @SOURCEDIR@

mpiexec @SIMFACTORY@ run @SIMULATION_NAME@ --machine=@MACHINE@ --restart-id=@RESTART_ID@ @FROM_RESTART_COMMAND@ < /dev/null > @RUNDIR@/@SIMULATION_NAME@.out 2> @RUNDIR@/@SIMULATION_NAME@.err

