
[hn1.lnmiit.ac.in]

# Machine description
nickname        = hn1.lnmiit.ac.in
name            = hn1.lnmiit.ac.in
location        = somewhere
description     = Whatever
status          = personal

# Access to this machine
hostname        = hn1.lnmiit.ac.in
aliaspattern    = ^generic\.some\.where$

# Source tree management
sourcebasedir   = /home/himanshu/Backup
optionlist      = /home/himanshu/Backup/Cactus/repos/simfactory2/mdb/optionlists/fedora.cfg
submitscript    = hpc_job.sub
runscript       = /home/himanshu/Backup/Cactus/repos/simfactory2/mdb/runscripts/hpc_job_r.run
make            = make -j4
basedir         = /home/himanshu/simulations
ppn             = 20
max-num-threads = 1	
num-threads     = 1	
nodes           = 6	
memory		= 994912
min-ppn         = 1
allocation      = UNKNOWN-ALLOCATION
queue           = batch
submit          = qsub @SCRIPTFILE@
getstatus       = qstat @JOB_ID@
stop            = qdel @JOB_ID@
submitpattern   = ^(\d+)\.
statuspattern   = ^@JOB_ID@[. ]
queuedpattern   = " Q "
runningpattern  = " R "
holdingpattern  = " H "
exechost        = qstat -f @JOB_ID@ #?
exechostpattern = exec_host = (\w+)/ #?
stdout          = cat @SIMULATION_NAME@.out
stderr          = cat @SIMULATION_NAME@.err
stdout-follow   = tail -n 100 -f @SIMULATION_NAME@.out @SIMULATION_NAME@.err
