#! /bin/bash
#PBS -A m2775
#PBS -q debug
#PBS -r n
#PBS -l walltime=0:30:00
#PBS -l mppwidth=64
#PBS -l proc=haswell
#PBS 
#PBS -N illinois11_wB_540_test
#PBS -m abe
#PBS -o /global/cscratch1/sd/chlin/simulations2/illinois11_wB_540_test/output-0000/illinois11_wB_540_test.out
#PBS -e /global/cscratch1/sd/chlin/simulations2/illinois11_wB_540_test/output-0000/illinois11_wB_540_test.err
cd /global/homes/c/chlin/et/Cactus
/global/u1/c/chlin/et/Cactus/repos/simfactory2/bin/sim run illinois11_wB_540_test --machine=cori --restart-id=0 
