[marenostrum5-cuda]

# Machine description
nickname        = marenostrum5ac
name            = Marenostrum5ac
location        = BSC
description     = our hope
status          = experimental

# Access to this machine
hostname        = alogin1.bsc.es
rsynccmd	= /usr/bin/rsync
aliaspattern	= ^alogin1.bsc.es$

envsetup = <<EOT
   unset MPI
EOT


# Source tree management
sourcebasedir   = /home/uib/uib416720/ETK2024/CarpetX
optionlist      = marenostrum5.cfg
submitscript    = marenostrum5.sub
runscript       = marenostrum5.run
make            = make -j8
basedir         = /gpfs/scratch/ice69/alejandra/simulations
ppn             = 80
max-num-threads = 100
num-threads     = 2

nodes           = 8
memory		= 400

allocation	= NO_ALLOCATION
queue		= acc_debug

submit          = sbatch @SCRIPTFILE@; sleep 5
getstatus       = squeue -j  @JOB_ID@

# need to kill the whole set of processes descending from @JOB_ID@, not just the
# (simfactory) top-level process
stop            = scancel @JOB_ID@
submitpattern   = Job (.*) is submitted
statuspattern   = '@JOB_ID@'
queuedpattern   = ' PD '
runningpattern  = ' (CF|CG|R|TO) '
holdingpattern  = ' S '

stdout          = cat @SIMULATION_NAME@.out
stderr          = cat @SIMULATION_NAME@.err
stdout-follow   = tail -n 100 -f @SIMULATION_NAME@.out @SIMULATION_NAME@.err
