
[hn1.lnmiit.ac.in]

# Machine description
nickname        = hn1.lnmiit.ac.in
name            = hn1.lnmiit.ac.in
location        = somewhere
description     = Whatever
status          = personal

# Access to this machine
hostname        = hn1.lnmiit.ac.in
aliaspattern    = ^generic\.some\.where$

# Source tree management
sourcebasedir   = /home/himanshu/Backup
optionlist      = /home/himanshu/Backup/Cactus/repos/simfactory2/mdb/optionlists/fedora.cfg
submitscript    = generic.sub
runscript       = /home/himanshu/Backup/Cactus/repos/simfactory2/mdb/runscripts/debian.sh
make            = make -j4
basedir         = /home/himanshu/simulations
ppn             = 20
max-num-threads = 40
num-threads     = 10
nodes           = 6
memory		= 294912
min-ppn         = 1
allocation      = NO_ALLOCATION
submit          = exec @SCRIPTFILE@ < /dev/null > /dev/null 2> /dev/null & echo $!
getstatus       = ps @JOB_ID@
stop            = kill @JOB_ID@
submitpattern   = (.*)
statuspattern   = "^ *@JOB_ID@ "
queuedpattern   = $^
runningpattern  = ^
holdingpattern  = $^
exechost        = echo localhost
exechostpattern = (.*)
stdout          = cat @SIMULATION_NAME@.out
stderr          = cat @SIMULATION_NAME@.err
stdout-follow   = tail -n 100 -f @SIMULATION_NAME@.out @SIMULATION_NAME@.er6