[stampede3-skx]

# last-tested-on: 2024-04-19
# last-tested-by: 

user 		= <user>

# Machine description
nickname        = stampede3-skx
name            = Stampede3 SkyLake
location        = TACC
description     = A very large Linux cluster at TACC
webpage         = https://portal.tacc.utexas.edu/user-guides/stampede3
status          = experimental

# Access to this machine
hostname        = stampede3.tacc.utexas.edu
envsetup        = <<EOT
    module unload boost || true
    module unload python2 || true
    module unload petsc || true
    module unload gsl || true
    module unload hdf5 || true
    module unload papi || true
    module unload impi || true
    module unload intel || true
    module load intel/24.0 && # alternate: gcc/13.2.0
    module load impi/21.11 && # alternate: mvapich/3.0
    module load python/3.9.18 &&
    module load gsl/2.7.1 &&
    module load hdf5/1.14.3 &&
    module load boost/1.85.0 &&
    module load papi/7.1.0 &&
    module load petsc/3.20-complex
EOT
# leave this empty so that it never matches and does not interfere with the KNL
# entry
# login[1234]\.stampede2\.tacc\.utexas\.edu$

aliaspattern    = ^login[12345]\.stampede3\.tacc\.utexas\.edu$ 

# Source tree management
# $HOME is not large enough
sourcebasedir   = /work2/09313/<user>/stampede3/einstein
disabled-thorns = <<EOT
EOT
enabled-thorns = <<EOT
EOT
optionlist      = stampede3-skx.cfg
submitscript    = stampede3-skx.sub
runscript       = stampede3-skx.run
makejobs        = 4
make            = make -j@MAKEJOBS@

# Simulation management  ##### NEEDS EDITING ####
basedir         = /scratch/09313/<user>/simulations
cpu             = Intel Xeon Platinum 8160 ("Skylake")
cpufreq         = 2.1 
flop/cycle      = 16
ppn             = 48
spn             = 2
mpn             = 2
max-num-threads = 48
# James Healy tested on 2018-02-19 and found best performance for 24MPI ranks
# per node when using hwloc: 24 MPI x 2 OMP_THREADS
num-threads     = 2
memory          = 196608 # units? = 48 * 2^12 = 48 * 4kb?
nodes           = 1736
min-ppn         = 48
allocation      = <allocation>
queue           = skx
maxwalltime     = 48:00:00      # development has 4:0:0
maxqueueslots   = 25            # there are 50, but jobs can take 2 slots
submit          = sbatch @SCRIPTFILE@; sleep 5 # sleep 60
getstatus       = squeue -j @JOB_ID@
stop            = scancel @JOB_ID@
submitpattern   = Submitted batch job ([0-9]+)
statuspattern   = '@JOB_ID@ '
queuedpattern   = ' PD '
runningpattern  = ' (CF|CG|R|TO) '
holdingpattern  = '\(JobHeldUser\)'
exechost        = hostname
exechostpattern = ^(\S+)
stdout          = cat @SIMULATION_NAME@.out
stderr          = cat @SIMULATION_NAME@.err
stdout-follow   = tail -n 100 -f @SIMULATION_NAME@.out @SIMULATION_NAME@.err
